export type Locale = "en" | "fr" | "es";

export const translations = {
  en: {
    nav: {
      explore: "Explore",
      hostCta: "Host a Jaifferson",
    },
    hero: {
      label: "Intelligence for high-stakes conversations",
      title1: "The room talks.",
      title2: "Jaifferson",
      titleEmphasis: "remembers.",
      desc: "Record, transcribe, and analyse structured dinners and calls between founders, operators, and investors. Receive a global session report and a private psychological synthesis for every participant.",
      ctaHost: "Host a Jaifferson",
      ctaExplore: "Explore sessions",
    },
    how: {
      label: "How it works",
      heading: "Two tracks. One platform.",
      host: {
        title: "For hosts",
        steps: [
          { title: "Propose a topic", desc: "Describe your subject. Jaifferson refines it and generates onboarding questions for applicants." },
          { title: "Curate the table", desc: "Review applications. Read each answer. Accept or decline. You decide who gets a seat." },
          { title: "Host the call", desc: "Join a Google Meet. Fireflies records and transcribes everything automatically." },
          { title: "Receive the reports", desc: "A global synthesis for the group, plus a private psychological profile for every participant — generated by AI." },
        ],
      },
      participant: {
        title: "For participants",
        steps: [
          { title: "Discover a session", desc: "Browse upcoming public Jaiffersons by topic, date, or host. Find the table that fits you." },
          { title: "Apply", desc: "Answer the host's onboarding questions. Share your background. The host reviews and decides." },
          { title: "Show up and contribute", desc: "Join the call. Speak freely. The AI listens and attributes words to each speaker." },
          { title: "Get your synthesis", desc: "Receive a private report: your archetype, your patterns, what the room revealed about you." },
        ],
      },
    },
    showcase: {
      label: "From the first session",
      heading: "What a Jaifferson produces",
      desc: "After each session, every participant receives a shared reading of the room and a private map of where they stand in it.",
      stats: [
        { value: "6", label: "participants" },
        { value: "87min", label: "of conversation" },
        { value: "12", label: "pages of reports" },
      ],
    },
    upcoming: {
      label: "Upcoming",
      heading: "Join a Jaifferson",
      empty: "No public sessions yet. Be the first to host one.",
      ctaHost: "Host the first one →",
    },
    finalCta: {
      heading: "The unit of value is not the meeting.",
      sub: "It is what the meeting reveals.",
      ctaHost: "Host a Jaifferson",
      ctaExplore: "Explore sessions",
    },
    footer: {
      brand: "Jaifferson",
      right: "by Quentin Cloarec",
    },
  },

  fr: {
    nav: {
      explore: "Explorer",
      hostCta: "Créer un Jaifferson",
    },
    hero: {
      label: "L'intelligence des conversations à fort enjeu",
      title1: "La salle parle.",
      title2: "Jaifferson",
      titleEmphasis: "retient.",
      desc: "Enregistrez, transcrivez et analysez des dîners et appels structurés entre fondateurs, opérateurs et investisseurs. Recevez un rapport de session global et une synthèse psychologique privée pour chaque participant.",
      ctaHost: "Créer un Jaifferson",
      ctaExplore: "Explorer les sessions",
    },
    how: {
      label: "Comment ça marche",
      heading: "Deux parcours. Une plateforme.",
      host: {
        title: "Pour les hôtes",
        steps: [
          { title: "Proposez un sujet", desc: "Décrivez votre thème. Jaifferson le reformule et génère des questions d'onboarding pour les candidats." },
          { title: "Composez la table", desc: "Examinez les candidatures. Lisez chaque réponse. Acceptez ou refusez. Vous décidez qui s'assoit." },
          { title: "Animez l'appel", desc: "Rejoignez un Google Meet. Fireflies enregistre et transcrit tout automatiquement." },
          { title: "Recevez les rapports", desc: "Une synthèse globale pour le groupe, plus un profil psychologique privé pour chaque participant — généré par l'IA." },
        ],
      },
      participant: {
        title: "Pour les participants",
        steps: [
          { title: "Découvrez une session", desc: "Parcourez les Jaiffersons publics à venir par sujet, date ou hôte. Trouvez la table qui vous correspond." },
          { title: "Postulez", desc: "Répondez aux questions de l'hôte. Partagez votre parcours. L'hôte examine et décide." },
          { title: "Participez et contribuez", desc: "Rejoignez l'appel. Parlez librement. L'IA écoute et attribue les mots à chaque intervenant." },
          { title: "Recevez votre synthèse", desc: "Un rapport privé : votre archétype, vos schémas, ce que la salle a révélé sur vous." },
        ],
      },
    },
    showcase: {
      label: "De la première session",
      heading: "Ce que produit un Jaifferson",
      desc: "Après chaque session, chaque participant reçoit une lecture partagée de la salle et une carte privée de sa position.",
      stats: [
        { value: "6", label: "participants" },
        { value: "87min", label: "de conversation" },
        { value: "12", label: "pages de rapports" },
      ],
    },
    upcoming: {
      label: "À venir",
      heading: "Rejoindre un Jaifferson",
      empty: "Pas encore de sessions publiques. Soyez le premier à en créer une.",
      ctaHost: "Créer le premier →",
    },
    finalCta: {
      heading: "L'unité de valeur n'est pas la réunion.",
      sub: "C'est ce qu'elle révèle.",
      ctaHost: "Créer un Jaifferson",
      ctaExplore: "Explorer les sessions",
    },
    footer: {
      brand: "Jaifferson",
      right: "par Quentin Cloarec",
    },
  },

  es: {
    nav: {
      explore: "Explorar",
      hostCta: "Crear un Jaifferson",
    },
    hero: {
      label: "Inteligencia para conversaciones de alto impacto",
      title1: "La sala habla.",
      title2: "Jaifferson",
      titleEmphasis: "recuerda.",
      desc: "Graba, transcribe y analiza cenas y llamadas estructuradas entre fundadores, operadores e inversores. Recibe un informe global de sesión y una síntesis psicológica privada para cada participante.",
      ctaHost: "Crear un Jaifferson",
      ctaExplore: "Explorar sesiones",
    },
    how: {
      label: "Cómo funciona",
      heading: "Dos caminos. Una plataforma.",
      host: {
        title: "Para anfitriones",
        steps: [
          { title: "Propón un tema", desc: "Describe tu tema. Jaifferson lo reformula y genera preguntas de onboarding para los candidatos." },
          { title: "Cura la mesa", desc: "Revisa las candidaturas. Lee cada respuesta. Acepta o rechaza. Tú decides quién se sienta." },
          { title: "Dirige la llamada", desc: "Únete a un Google Meet. Fireflies graba y transcribe todo automáticamente." },
          { title: "Recibe los informes", desc: "Una síntesis global para el grupo, más un perfil psicológico privado para cada participante — generado por IA." },
        ],
      },
      participant: {
        title: "Para participantes",
        steps: [
          { title: "Descubre una sesión", desc: "Explora los Jaiffersons públicos próximos por tema, fecha o anfitrión. Encuentra la mesa que te va." },
          { title: "Postúlate", desc: "Responde las preguntas del anfitrión. Comparte tu trayectoria. El anfitrión revisa y decide." },
          { title: "Participa y contribuye", desc: "Únete a la llamada. Habla libremente. La IA escucha y atribuye palabras a cada hablante." },
          { title: "Recibe tu síntesis", desc: "Un informe privado: tu arquetipo, tus patrones, lo que la sala reveló sobre ti." },
        ],
      },
    },
    showcase: {
      label: "De la primera sesión",
      heading: "Lo que produce un Jaifferson",
      desc: "Después de cada sesión, cada participante recibe una lectura compartida de la sala y un mapa privado de su posición.",
      stats: [
        { value: "6", label: "participantes" },
        { value: "87min", label: "de conversación" },
        { value: "12", label: "páginas de informes" },
      ],
    },
    upcoming: {
      label: "Próximamente",
      heading: "Únete a un Jaifferson",
      empty: "Aún no hay sesiones públicas. Sé el primero en crear una.",
      ctaHost: "Crear el primero →",
    },
    finalCta: {
      heading: "La unidad de valor no es la reunión.",
      sub: "Es lo que revela.",
      ctaHost: "Crear un Jaifferson",
      ctaExplore: "Explorar sesiones",
    },
    footer: {
      brand: "Jaifferson",
      right: "por Quentin Cloarec",
    },
  },
};
